# Generated by Django 5.2.4 on 2026-06-23 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_income', models.PositiveIntegerField(blank=True, help_text='연봉 단위: 만원', null=True)),
                ('job', models.CharField(blank=True, max_length=50)),
                ('main_bank', models.CharField(blank=True, max_length=50)),
                ('investment_tendency', models.CharField(blank=True, max_length=50)),
                ('preferred_period', models.CharField(blank=True, max_length=50)),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('personal_info_agree', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
