# Generated by Django 5.2.4 on 2026-06-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='investment_tendency',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='job',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_period',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='purpose',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lump_sum_amount',
            field=models.CharField(blank=True, choices=[('none', '없음'), ('under_100', '100만원 미만'), ('100_500', '100만원 이상 500만원 미만'), ('500_1000', '500만원 이상 1000만원 미만'), ('1000_3000', '1000만원 이상 3000만원 미만'), ('over_3000', '3000만원 이상')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_income_range',
            field=models.CharField(blank=True, choices=[('under_100', '100만원 미만'), ('100_200', '100만원 이상 200만원 미만'), ('200_300', '200만원 이상 300만원 미만'), ('300_400', '300만원 이상 400만원 미만'), ('400_500', '400만원 이상 500만원 미만'), ('over_500', '500만원 이상')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_saving_amount',
            field=models.CharField(blank=True, choices=[('under_10', '10만원 미만'), ('10_30', '10만원 이상 30만원 미만'), ('30_50', '30만원 이상 50만원 미만'), ('50_100', '50만원 이상 100만원 미만'), ('over_100', '100만원 이상')], max_length=20),
        ),
    ]
