# Generated by Django 5.2.4 on 2026-06-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productoption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productoption',
            name='rsrv_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='productoption',
            name='rsrv_type_nm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='productoption',
            unique_together={('product', 'intr_rate_type', 'rsrv_type', 'save_trm')},
        ),
    ]
